# Generated by Django 5.0.1 on 2024-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='species',
            field=models.CharField(default='Plant', max_length=60),
        ),
    ]
